name: CI/CD
on:
  workflow_dispatch:

permissions:
  # id-token: write
  contents: write
  packages: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: pnpm/action-setup@v4
      #   with:
      #     version: latest
      - uses: actions/setup-node@v4
      #   with:
      #     node-version: '24'
      #     registry-url: 'https://registry.npmjs.org'
      #     cache: 'pnpm'
      # - run: pnpm install --frozen-lockfile
      # - run: pnpm build
      # - run: pnpm publish --access public --no-git-checks
      - id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
  build-docker-images:
    runs-on: ubuntu-latest
    needs: create-tag
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: blitzbrowser
            image_suffix: blitzbrowser
            dockerfile: ./blitzbrowser/Dockerfile
            context: ./blitzbrowser
          - name: dashboard
            image_suffix: dashboard
            dockerfile: ./dashboard/Dockerfile
            context: ./dashboard
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
      # - uses: pnpm/action-setup@v4
      #   with:
      #     version: latest
      - uses: actions/setup-node@v4
      #   with:
      #     node-version: '24'
      #     registry-url: 'https://registry.npmjs.org'
      #     cache: 'pnpm'
      # - run: pnpm install --frozen-lockfile
      # - run: pnpm build
      # - run: pnpm publish --access public --no-git-checks
      - id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_suffix }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_suffix }}:${{ steps.package_version.outputs.VERSION }}